# Generated by Django 6.0.1 on 2026-01-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(choices=[('romans', 'Romans'), ('sf', 'Science Fiction'), ('technology', 'Technology'), ('history', 'Histoire'), ('fantasy', 'Fantasy')], default='romans', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('limited', 'Stock limité'), ('out', 'Rupture'), ('reserved', 'Réservé')], default='available', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
